const eyeColors = [
  "Zielony",
  "Szmaragdowy",
  "Jasnoniebieski",
  "Oceaniczny niebieski",
  "Jasnobrązowy",
  "Ciemnobrązowy",
  "Piwny",
  "Ciemnoszary",
  "Jasnoszary",
  "Różowy",
  "Żółty",
  "Fioletowy",
  "Czarny",
  "Odcienie szarości",
  "Tequila Sunrise",
  "Atomic",
  "Warp",
  "ECola",
  "Space Ranger",
  "Ying Yang",
  "Trafiony w dziesiątkę",
  "Jaszczurka",
  "Smok",
  "Pozaświatowy",
  "Koza",
  "Uśmiech",
  "Opanowany",
  "Demon",
  "Zainfekowany",
  "Obcy",
  "Nieumarły",
  "Zombie",
]

const featureNames = [
  "Szerokość nosa",
  "Wysokość dolnej części nosa",
  "Długość czubka nosa",
  "Głębokość mostka nosa",
  "Wysokość czubka nosa",
  "Złamany nos",
  "Wysokość brwi",
  "Głębokość brwi",
  "Wysokość kości policzkowych",
  "Szerokość kości policzkowych",
  "Głębokość policzków",
  "Rozmiar oka",
  "Grubość warg",
  "Szerokość szczęki",
  "Kształt szczęki",
  "Wysokość brody",
  "Głębokość brody",
  "Szerokość brody",
  "Wklęsłość brody",
  "Szerokość szyi",
]

const headOverlays = [
  { name: "Skazy", min: "0", maks: "23" },
  { name: "Broda", min: "0", maks: "28" },
  { name: "Brwi", min: "0", maks: "33" },
  { name: "Starzenie", min: "0", maks: "14" },
  { name: "Makijaż", min: "0", maks: "74" },
  { name: "Rumieńce", min: "0", maks: "32" },
  { name: "Karnacja", min: "0", maks: "11" },
  { name: "Uszkodzenia słoneczne", min: "0", maks: "10" },
  { name: "Szminka", min: "0", maks: "9" },
  { name: "Pieprzyki/Skazki", min: "0", maks: "17" },
  { name: "Włosy na klatce piersiowej", min: "0", maks: "16" },
  { name: "Skazy na ciele", min: "0", maks: "11" },
  { name: "Dodaj skazy na ciele", min: "0", maks: "1" },
]

const g_Heritages = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 42, 43, 44, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45]

export {
  eyeColors,
  featureNames,
  headOverlays,
  g_Heritages,
}
